name = "adelflo-worker"
main = "worker.js"
compatibility_date = "2026-07-01"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "img"

[vars]
PUBLIC_BASE_URL = "https://pub-a82833c98a254446bf65db1f16fa9b05.r2.dev"